### ISSUE TITLE
Error Tidak bisa insert flag 'Export data transaksi'

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/S2P#1]

**Comment by hendrisulistiono** [comment]
Di log export selalu tampil informasi dibawah ini :

"Error Tidak bisa insert flag 'Export data transaksi'"

kalau memang hanya warning seharusnya pesannya warning atau hanya informasi saja

**Comment by ntoenk1186** [comment]
- [x] Merubah message untuk perubahan flag status transaksi export

**Comment by ntoenk1186** [comment]
- Test pertama dengan database SQL Server 2012 IP 10.0.0.105
  - Result : FAILED
  - Error : 

```
[2014-11-26 10:56:43,286 ExportController ERROR] General SQL Server error: Check messages from the SQL Server [515] (severity 16) [INSERT INTO bcwo (wonum,itemnum,quantity,issuetype,actualdate,storeloc,enterby,issueto,memo) 
                VALUES ('8289','10124','1.000','ISSUE','2014-10-13 16:28:25','ABH','MAXADMIN','ACHMAD.ISKANDAR','');]
```
- Problem : 
  - Table bcwo belum update dengan struktur yang terbaru

**Comment by ntoenk1186** [comment]
- [x] Hapus column conditioncode dari database SQL Server pada table bcwo

**Comment by ntoenk1186** [comment]
- Test kedua dengan database SQL Server 2012 IP 10.0.0.105
  - Result : PASSED

**Comment by ntoenk1186** [comment]
hasil build [wic export](http://trading.quantumfin.com/binary/wic/wic_export/wic_export-1.0.6-SNAPSHOT.bin)

**Comment by cyberspaces14** [comment]
Test export data dan cek log tidak kerjadian lagi test : Passed
