### ISSUE TITLE
Unable to connect: Adaptive Server is unavailable or does not exist

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/S2P#2]

**Comment by hendrisulistiono** [comment]
Check ke log ada informasi seperti berikut

"Unable to connect: Adaptive Server is unavailable or does not exist"

apakah ini ada hubungan dengan data tidak export, detailnya silahkan lihat di log

**Comment by ntoenk1186** [comment]
- log informasi di atas memang tidak melakukan export data tetapi tidak merubah status export item number yang ditransaksikan
- Kemungkinan SQL Server maximo sedang down sehingga tidak bisa melakukan koneksi
