### ISSUE TITLE
Beberapa transaksi WO tidak export ke table bridging

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/S2P#3]

**Comment by hendrisulistiono** [comment]
Menurut laporan dari team gudang beberapa transaksi dari nomor WO berikut tidak bisa masuk ke table bridging maximo : 
- 8283
- 8281
- 9063

Checkny langsung ssh ke cilacap

**Comment by ntoenk1186** [comment]
- Data yang masuk ke table bridging (192.168.0.190) hanya transaksi tanggal 24-11-2014 sampai sekarang
- Perlu dikonfirmasikan : 
  - apakah perubahan vmware maximo hanya perubahan IP saja atau menggunakan vmware yang baru?

**Comment by hendrisulistiono** [comment]
Sudah tidak bisa dilacak karena, konfigurasi di maximonya development tapi transaksi mereka masuk ke production. Jadi belum bisa dipastikan laporannya
