### ISSUE TITLE
Receive PO validasinya tidak jalan

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/S2P#4]

**Comment by hendrisulistiono** [comment]
Ketika melakukan transaksi receiving PO terdapat validasi antara order qty dengan receive qty, dimana receive qty tidak boleh melebihi order qty. Validasi ini berjalan ketika dalam 1 transaksi, akan tetapi jika berbeda transaksi validasi ini tidak berjalan.

**Comment by daori** [comment]
Cek Config pada database (true/false) untuk mengecek ke transaksi
- [x] Menambahkan validasi untuk pengecekan po pada ItemBarcodePO  
  - yang sudah ada validasi ke transaksi ada pada ReturnPO dan ReturnWO
  - Transaction Order quantity tidak boleh melebihi qty pada Poline
  - Pengecekan item, pada transaksi PO, cek po dan itemNumber pada TrxPoDetail 
    - Rumus (poline.orderqty - sum(trxPoDetail.issueQty)) = max item yang bisa di transaksikan

**Comment by ntoenk1186** [comment]
Test Result : PASSED

**Comment by cyberspaces14** [comment]
Test  transaksi PO qty input  tidak melebih PO : Passed
