### ISSUE TITLE
Gagal insert ke maximo

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/S2P#6]
[2014-12-02 12:00:01,585 ExportController ERROR] General SQL Server error: Check messages from the SQL Server [512](severity 16) [INSERT INTO bcpo (ponum,itemnum,quantity,issuetype,actualdate,tostoreloc,enterby,remark)
                VALUES ('11824','1300','20.000','RECEIPT','2014-11-17 08:38:21','WH','ROSIKIN','-');]
 exception 'ErrorException' with message 'General SQL Server error: Check messages from the SQL Server [512](severity 16) [INSERT INTO bcpo (ponum,itemnum,quantity,issuetype,actualdate,tostoreloc,enterby,remark)
                VALUES ('11824','1300','20.000','RECEIPT','2014-11-17 08:38:21','WH','ROSIKIN','-');]' in /opt/data/site/wic/wic_export/release-l

**Comment by ntoenk1186** [comment]
- Jika dilihat dari log di atas, terjadi error code 512 pada database MAXIMO (SQL Server). Dimana error message untuk error code tersebut adalah `Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.`. ([List Error Code SQL Server](http://infocenter.sybase.com/archive/index.jsp?topic=/com.sybase.infocenter.dc36584.1260/html/iqerror/Errsybcode.htm))
  - Error bisa dilihat di file [log freetds.log](https://drive.google.com/a/netzme.id/file/d/0B7Y9d4BGDgyzWkVUbVY2VzZhUE0/view?usp=sharing) yang ada di path `/opt/data/logs/`
- SQL yang dijalankan : 

```
INSERT INTO bcpo (ponum,itemnum,quantity,issuetype,actualdate,tostoreloc,enterby,remark) VALUES ('11824','16992','320.000','RECEIPT','2014-11-17 08:36:35','WH','ROSIKIN','-');
INSERT INTO bcpo (ponum,itemnum,quantity,issuetype,actualdate,tostoreloc,enterby,remark) VALUES ('11824','1300','20.000','RECEIPT','2014-11-17 08:38:21','WH','ROSIKIN','-');
```
- Error muncul/terjadi ketika SQL kedua djalankan.
- Karena eksekusi dalam bentuk `transaction`, maka SQL yang telah berhasil sebelumnya akan `rollback`

**Comment by hendrisulistiono** [comment]
Kemungkinan di maximo ada perubahan nama field yang meng-akibatkan error ini muncul, karena di trigger-nya nama field-nya belum dirubah
