### ISSUE TITLE
Gagal tutup buku

### ISSUE THREAD

**Issue by hendrisulistiono** [netzme/S2P#7]
Waktu UAT bersama tanggal 03/12/2014 kemarin terjadi Gagal Tutup Buku, padahal sudah di mapping semua transaksi-nya

**Comment by katenzo** [comment]
di Log ada Gagal Insert karena ada data tanpa info month & year di proses create data history
- Cek di pembuatan data history

**Comment by katenzo** [comment]
Sudah di Deploy dI 10.0.0.60  versi wic_web-0.0.22-SNAPSHOT
- Database di switch ke wic_cilacap, untuk menyamakan kondisi data denagn cilacap , sebelum database di clear
- Jika Test ini lolos, bisa dilakukan juga untuk scenario hapus data

**Comment by daori** [comment]
saya test dengan  menghapus tutup buku di table close_book untuk bulan sebelumnya. Dialog tutup buku dan redirect ke desktop
